### ISSUE TITLE
Fingerprinting doesn't work with font files @font-face

### ISSUE THREAD

**Issue by bogdansoare** [rickharrison/broccoli-asset-rev#73]
I need to serve fontawesome from my CDN, but broccoli-asset-rev ignores it in my CSS.
I tried referencing the font with different urls /fonts, fonts/, ../fonts/ but it doesn't work.

I saw that there was a closed issue rickharrison/broccoli-asset-rev#42 with the same problems, but for me it doesn't work. 

```javascript
// ember-cli-build.js
fingerprint: {
      enabled: isProductionLikeBuild,
      prepend: 'http://name.s3.amazonaws.com/',
      extensions: ['js', 'css', 'png', 'jpg', 'gif', 'svg', 'eot', 'ttf', 'woff2', 'woff']
}
```
```scss
// app.scss
@font-face {
    font-family: FontAwesome;
    src: url(/fonts/fontawesome-webfont.eot?v=4.4.0);
    src: url(/fonts/fontawesome-webfont.eot?#iefix&v=4.4.0) format("embedded-opentype"),url(/fonts/fontawesome-webfont.woff2?v=4.4.0) format("woff2"),url(/fonts/fontawesome-webfont.woff?v=4.4.0) format("woff"),url(/fonts/fontawesome-webfont.ttf?v=4.4.0) format("truetype"),url(/fonts/fontawesome-webfont.svg?v=4.4.0#fontawesomeregular) format("svg");
    font-weight: 400;
    font-style: normal
}
```
